name: CI

on:
    push:
        branches: main
        paths: ['**.cpp', '**.h', '**CMakeLists.txt'] 
    pull_request:
        branches: main
        paths: ['**.cpp', '**.h', '**CMakeLists.txt']

jobs:
    build-and-test:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest] 
        runs-on: ${{ matrix.os }}
        steps:
            # Start and join the Spigot Server
            - name: Set up Minecraft testing environment
              uses: nhatdongdang/mc-env-setup@v1

            # Checkout the mcpp repository for building and testing
            - name: Checkout mcpp
              uses: actions/checkout@v4

            # Build files using CMake
            - name: Build file
              run: cmake -Bbuild

            - name: Install library
              working-directory: ./build
              run: sudo make install
            
            - name: Compile and link
              run: g++ -std=c++17 -lmcpp example/test_link.cpp -o example/test_link && test/test_link

            # Run the test suite using ctest
            - name: Run test suite
              working-directory: ./build
              run: make test_suite && ctest -R full -V
            
            
